services:
  teldrive:
    image: ghcr.io/rizu491na/teldrive-jp
    restart: always
    container_name: teldrive
    networks:
     - postgres
    volumes:
      - ./config.toml:/config.toml
      - ./session.db:/session.db
    ports:
      - 8080:8080
networks:
  postgres:                                 
    external: true
